# Generated by Django 4.2.7 on 2024-01-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-create_date']},
        ),
    ]
