# Generated by Django 4.2.7 on 2024-04-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve',
            new_name='approved',
        ),
    ]
