# Generated by Django 4.2.7 on 2024-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_approve_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='blog/default.jpeg', upload_to='blog/'),
        ),
    ]
