# Generated by Django 4.2.7 on 2024-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/default.jpeg', upload_to='blog/'),
        ),
    ]
